wifi:
  fast_connect: true
  ssid:
  password: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_signal_sensor