---
substitutions:
  board: esp32dev

packages:
  base: !include common-base.yaml

esp32:
  board: ${board}
  framework:
    type: esp-idf

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic