---
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  

packages:
  ota: !include common/ota.yaml
  sensors: !include common/sensors.yaml
  binary_sensors: !include common/binary_sensors.yaml
  logger: !include common/logger.yaml
  api: !include common/api.yaml