# Bluetooth proxy using an ESP32 Wroom with BLE and Wifi



substitutions:
  name: "bt-proxy"

  project_name: azndibs.btproxy
  project_ver: "1.1.2"

esphome:
  name: ${name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_ver}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  #level: DEBUG
  #level: VERBOSE
  level: VERY_VERBOSE


api:


ota:



# wifi component
wifi:
  fast_connect: true
  ssid:
  password:
  ap:
    ssid: "Bluetooth-Proxy Fallback Hotspot"
    password:
#########################################################################
#### ADD YOUR WIFI COMPONENT HERE, KEEP FAST_CONNECT FOR HIDDEN SSID ####
#########################################################################
improv_serial:

captive_portal:

dashboard_import:
  package_import_url: github://AznDibs/esphome_configs/bt-proxy.yaml@main
  import_full_config: false

# ble component
esp32_ble_tracker:
  scan_parameters:
    # We currently use the defaults to ensure Bluetooth
    # can co-exist with WiFi In the future we may be able to
    # enable the built-in coexistence logic in ESP-IDF
    active: false

bluetooth_proxy:
  active: true



# sensors component
sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    id: wifi_signal_sensor
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor

# binary sensors component
binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic

  - platform: restart
    name: "Restart"
    entity_category: diagnostic