substitutions:
  name: "bluetooth-proxy"
  friendly_name: Bluetooth Proxy
  board: esp32dev

packages:
  bt-proxy: !include modules/devices/bt-proxy.yaml

esphome:
  project: bt-proxy
  version: "1.0"

# Enable logging
logger:
  #level: DEBUG
  #level: VERBOSE
  level: VERY_VERBOSE

api:

ota:

dashboard_import:
  package_import_url: github://AznDibs/esphome_configs/template_bluetooth_proxy.yaml@main


wifi:
  ssid:
  password:
  ap:
    password: